# Generated by Django 3.1.3 on 2022-08-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donadona', '0002_auto_20220819_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='star_time',
            new_name='start_time',
        ),
    ]
