# Generated by Django 3.1.3 on 2022-09-01 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donadona', '0004_auto_20220902_0203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='help_star_time',
            new_name='help_start_time',
        ),
    ]
