# Generated by Django 3.1.3 on 2022-09-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donadona', '0006_auto_20220902_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='help_start_time',
        ),
        migrations.AddField(
            model_name='post',
            name='help_date',
            field=models.CharField(default='YYYY-MM-DD', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='help_time',
            field=models.CharField(default='HH:MM', max_length=20),
        ),
        migrations.AlterField(
            model_name='day',
            name='day_week',
            field=models.CharField(choices=[('월요일', '월요일'), ('화요일', '화요일'), ('수요일', '수요일'), ('목요일', '목요일'), ('금요일', '금요일'), ('토요일 ', '토요일'), ('일요일 ', '일요일')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='help_day_week',
            field=models.CharField(choices=[('월요일', '월요일'), ('화요일', '화요일'), ('수요일', '수요일'), ('목요일', '목요일'), ('금요일', '금요일'), ('토요일 ', '토요일'), ('일요일 ', '일요일')], max_length=20),
        ),
    ]
