# Generated by Django 3.1.3 on 2022-09-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donadona', '0007_auto_20220904_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
