# Generated by Django 3.1.3 on 2022-09-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donadona', '0009_auto_20220908_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='able_category',
            field=models.CharField(choices=[('생활', '생활'), ('환경', '환경'), ('식사', '식사'), ('동행', '동행'), ('안전', '안전'), ('운동', '운동'), ('의료', '의료'), ('상담', '상담'), ('문화', '문화'), ('교육', '교육'), ('정서', '정서'), ('취미', '취미'), ('외국어', '외국어'), ('IT', 'IT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='help_able_category',
            field=models.CharField(choices=[('생활', '생활'), ('환경', '환경'), ('식사', '식사'), ('동행', '동행'), ('안전', '안전'), ('운동', '운동'), ('의료', '의료'), ('상담', '상담'), ('문화', '문화'), ('교육', '교육'), ('정서', '정서'), ('취미', '취미'), ('외국어', '외국어'), ('IT', 'IT')], max_length=20),
        ),
    ]
